# Generated by Django 4.0.1 on 2022-01-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Secret Message',
                'verbose_name_plural': 'Secret Messages',
            },
        ),
    ]
